=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v1/electrical_properties_data_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "SamplesAnalysisID": {
            "type": "string",
            "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$"
        },
        "SamplesID": {
            "type": "string",
            "pattern": "^[\\w-.]+:master-data-Samples:[\\w\\-\\.\\:\\%]+:[0-9]*$"
        },
        "BrineConcentration": {
            "type": "object",
            "properties": {
                "Value": {
                    "type": "number"
                },
                "UnitOfMeasure": {
                    "type": "string",
                    "pattern": "^[\\w-.]:reference-data--UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                }
            }
        },
        "FormationFactor": {
            "type": "number"
        },
        "AdjustedFormationFactor": {
            "type": "number"
        },
        "CementationExponent": {
            "type": "number"
        },
        "AdjustedCemetationExponent": {
            "type": "number"
        },
        "SaturationExponent": {
            "type": "number"
        },
        "AdjustedSaturationExponent": {
            "type": "number"
        }
    },
    "required": [
        "SamplesAnalysisID",
        "SamplesID"
    ]
}

=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v1/electrical_properties_data_example.json
{
    "SamplesAnalysisID": "osdu:work-product-component--SamplesAnalysisID:dd76cf6c-226f-5636-ad1b-1ca0f8249cc8",
    "SamplesID": "osdu:master-data--Samples:4b",
    "BrineConcentration": {
        "Value": 22000,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:ppm"
    },
    "FormationFactor": 6.87,
    "AdjustedFormationFactor": 7.27,
    "CementationExponent": 1.72,
    "AdjustedCemetationExponent": 1.78,
    "SaturationExponent": 2.03,
    "AdjustedSaturationExponent": 2.32
}
