=== sharad-adapts/rafs-ddms/tests/test_api/test_routes/osdu/schemas/samplesanalysesreport.json
{
    "x-osdu-inheriting-from-kind": [
        {
            "kind": "osdu:wks:AbstractWPCGroupType:1.2.0",
            "name": "WorkProductComponent"
        }
    ],
    "x-osdu-license": "Copyright 2023, The Open Group \\nLicensed under the Apache License, Version 2.0 (the \"License\"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "x-osdu-schema-source": "osdu:wks:work-product-component--SamplesAnalysesReport:1.0.0",
    "description": "Attributes needed to find and retrieve a delivered report containing rock and/or fluid sample analysis data. Often this report contains more than one data frame of analysis data and/or more than one Analysis Family. Examples of this could include end-of-well reports, well completion reports, regional multi-well studies, or SCAL reports. This report can be decomposed into analysis sets via the SamplesAnalysis work-product-component. In other cases, this report contains part of a dataset which could then be aggregated into a SamplesAnalysis work-product-component.",
    "title": "SamplesAnalysesReport",
    "type": "object",
    "x-osdu-review-status": "Accepted",
    "required": [
        "kind",
        "acl",
        "legal"
    ],
    "x-osdu-virtual-properties": {
        "data.VirtualProperties.DefaultName": {
            "type": "string",
            "priority": [
                {
                    "path": "data.Name"
                }
            ]
        },
        "data.VirtualProperties.DefaultLocation": {
            "type": "object",
            "priority": [
                {
                    "path": "data.SpatialLocation"
                }
            ]
        }
    },
    "additionalProperties": false,
    "properties": {
        "ancestry": {
            "description": "The links to data, which constitute the inputs, from which this record instance is derived.",
            "title": "Ancestry",
            "$ref": "#/definitions/osdu:wks:AbstractLegalParentList:1.0.0"
        },
        "data": {
            "allOf": [
                {
                    "$ref": "#/definitions/osdu:wks:AbstractCommonResources:1.0.0"
                },
                {
                    "$ref": "#/definitions/osdu:wks:AbstractWPCGroupType:1.2.0"
                },
                {
                    "$ref": "#/definitions/osdu:wks:AbstractWorkProductComponent:1.1.0"
                },
                {
                    "type": "object",
                    "title": "IndividualProperties",
                    "properties": {
                        "LaboratoryIDs": {
                            "x-osdu-attribution-publication": "OSDU",
                            "x-osdu-attribution-revision": "Evergreen",
                            "x-osdu-attribution-authority": "OpenGroup",
                            "description": "OSDU Record IDs for the laboratories used to conduct the sample analyses contained in this report. This could represent the laboratory company or the laboratory branch.",
                            "type": "array",
                            "title": "Laboratory ID",
                            "items": {
                                "x-osdu-relationship": [
                                    {
                                        "EntityType": "Organisation",
                                        "GroupType": "master-data"
                                    }
                                ],
                                "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Organisation:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                                "type": "string"
                            }
                        },
                        "SampleIDs": {
                            "description": "OSDU Record IDs for the Rock and/or Fluid Sample or Samples on which this batch or batches of analysis were performed.",
                            "type": "array",
                            "items": {
                                "x-osdu-relationship": [
                                    {
                                        "EntityType": "Sample",
                                        "GroupType": "master-data"
                                    }
                                ],
                                "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                                "type": "string"
                            },
                            "example": [
                                "namespace:master-data--Sample:Kentish-Knock-South-1_KK-16:",
                                "namespace:master-data--Sample:Kentish-Knock-South-1_KK-17:",
                                "namespace:master-data--Sample:Kentish-Knock-South-1_KK-21:"
                            ]
                        },
                        "DocumentSubject": {
                            "description": "A description text or an array of subjects covered by the document. If present this information must compliment the Tag and SubTitle",
                            "type": "string"
                        },
                        "NumberOfPages": {
                            "description": "Number of pages in the document, useful in cases where if it was described in the acquired manifest as opposed to a derived/calculated value",
                            "type": "integer"
                        },
                        "DocumentTypeID": {
                            "x-osdu-relationship": [
                                {
                                    "EntityType": "DocumentType",
                                    "GroupType": "reference-data"
                                }
                            ],
                            "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-DocumentType:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                            "description": "The kind of document--from a business standpoint, e.g., multi-well study, etc.",
                            "type": "string"
                        },
                        "DatePublished": {
                            "format": "date-time",
                            "description": "The date and time that the results of the analysis containing observed measurements or calculations was published",
                            "type": "string"
                        },
                        "LaboratoryNames": {
                            "description": "List of names of laboratories used to conduct the sample analyses contained in this report. This attribute is more freeform than Laboratory IDs and does not have relationships to OSDU Record IDs. This attribute exists to help with a low bar of ingestion but best practice is to resolve each of these to an OSDU Record ID in the LaboratoryIDs attribute.",
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "Remarks": {
                            "x-osdu-indexing": {
                                "type": "flattened"
                            },
                            "description": "An array containing operational or quality comments pertaining to the sample analysis represented by this work product component.",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/osdu:wks:AbstractRemark:1.0.0"
                            }
                        },
                        "DocumentLanguage": {
                            "description": "Document language as listed in the ISO 639-3 https://en.wikipedia.org/wiki/ISO_639, https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes",
                            "type": "string",
                            "example": "eng"
                        },
                        "ReportSampleIdentifiers": {
                            "description": "The names or identifiers of the analyzed samples in this report or document. These names or identifiers are often assigned by the laboratory. This list can be used to assist in locating the appropriate OSDU Sample records or to find the dataset in the parent report.",
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "example": [
                                "KK-16",
                                "KK-17",
                                "KK-21"
                            ]
                        },
                        "SamplesAnalysisCategoryTagIDs": {
                            "description": "List of higher level grouping terms that are often used within organisations to search for analysis types in addition to the formal Family and Method properties, but which are variable across organisations and therefore do not need to be governed strictly by the OSDU Forum. For example: SCAL, Static SCAL, Dynamic SCAL, Source Rock Analysis. We suggest you use a namespace, like the operators name, like “Shell.SCAL”. BP.SCAL, Equinor.SCAL, Chevron.SCAL, Exxon.SCAL.....",
                            "type": "array",
                            "items": {
                                "x-osdu-relationship": [
                                    {
                                        "EntityType": "SamplesAnalysisCategoryTag",
                                        "GroupType": "reference-data"
                                    }
                                ],
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-SamplesAnalysisCategoryTag:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                                "type": "string"
                            },
                            "example": [
                                "namespace:reference-data--SamplesAnalysisCategoryTag:ExxonMobil-SCAL:"
                            ]
                        },
                        "SubTitle": {
                            "description": "The sub-title of the document.",
                            "type": "string"
                        },
                        "DateModified": {
                            "format": "date-time",
                            "description": "The date and time that the document was last modified",
                            "type": "string"
                        },
                        "SampleAnalysisTypeIDs": {
                            "description": "A list of all sample analysis types represented by this report, whether the sample analysis type relates to Rock, Fluid, or both.",
                            "type": "array",
                            "items": {
                                "x-osdu-relationship": [
                                    {
                                        "EntityType": "SampleAnalysisType",
                                        "GroupType": "reference-data"
                                    }
                                ],
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-SampleAnalysisType:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                                "type": "string"
                            },
                            "example": [
                                "namespace:reference-data--SampleAnalysisType:Wettability.Amott-Harvey:"
                            ]
                        }
                    }
                },
                {
                    "type": "object",
                    "title": "ExtensionProperties",
                    "properties": {
                        "ExtensionProperties": {
                            "type": "object"
                        }
                    }
                }
            ]
        },
        "kind": {
            "pattern": "^[\\w\\-\\.]+:[\\w\\-\\.]+:[\\w\\-\\.]+:[0-9]+.[0-9]+.[0-9]+$",
            "description": "The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.",
            "title": "Entity Kind",
            "type": "string",
            "example": "osdu:wks:work-product-component--SamplesAnalysesReport:1.0.0"
        },
        "acl": {
            "description": "The access control tags associated with this entity.",
            "title": "Access Control List",
            "$ref": "#/definitions/osdu:wks:AbstractAccessControlList:1.0.0"
        },
        "version": {
            "format": "int64",
            "description": "The version number of this OSDU resource; set by the framework.",
            "title": "Version Number",
            "type": "integer",
            "example": 1562066009929332
        },
        "tags": {
            "description": "A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.",
            "additionalProperties": {
                "type": "string"
            },
            "title": "Tag Dictionary",
            "type": "object",
            "example": {
                "NameOfKey": "String value"
            }
        },
        "modifyUser": {
            "description": "The user reference, which created this version of this resource object. Set by the System.",
            "title": "Resource Object Version Creation User Reference",
            "type": "string",
            "example": "some-user@some-company-cloud.com"
        },
        "modifyTime": {
            "format": "date-time",
            "description": "Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
            "title": "Resource Object Version Creation DateTime",
            "type": "string",
            "example": "2020-12-16T11:52:24.477Z"
        },
        "createTime": {
            "format": "date-time",
            "description": "Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.",
            "title": "Resource Object Creation DateTime",
            "type": "string",
            "example": "2020-12-16T11:46:20.163Z"
        },
        "meta": {
            "description": "The Frame of Reference meta data section linking the named properties to self-contained definitions.",
            "title": "Frame of Reference Meta Data",
            "type": "array",
            "items": {
                "$ref": "#/definitions/osdu:wks:AbstractMetaItem:1.0.0"
            }
        },
        "legal": {
            "description": "The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
            "title": "Legal Tags",
            "$ref": "#/definitions/osdu:wks:AbstractLegalTags:1.0.0"
        },
        "createUser": {
            "description": "The user reference, which created the first version of this resource object. Set by the System.",
            "title": "Resource Object Creation User Reference",
            "type": "string",
            "example": "some-user@some-company-cloud.com"
        },
        "id": {
            "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysesReport:[\\w\\-\\.\\:\\%]+$",
            "description": "Previously called ResourceID or SRN which identifies this OSDU resource object without version.",
            "title": "Entity ID",
            "type": "string",
            "example": "namespace:work-product-component--SamplesAnalysesReport:b632082e-e5aa-5d92-96f5-e5e87c10780c"
        }
    },
    "$id": "https://schema.osdu.opengroup.org/json/work-product-component/SamplesAnalysesReport.1.0.0.json"
}

=== sharad-adapts/rafs-ddms/notebooks/wpc_payloads/samples_analyses_report.json
[
    {
        "id": "{data_partition_id}:work-product-component--SamplesAnalysesReport:SamplesAnalysesReport",
        "kind": "osdu:wks:work-product-component--SamplesAnalysesReport:1.0.0",
        "acl": {
            "viewers": [
                "{acl_viewers}"
            ],
            "owners": [
                "{acl_owners}"
            ]
        },
        "legal": {
            "legaltags": [
                "{legal_tag}"
            ],
            "otherRelevantDataCountries": [
                "US"
            ],
            "status": "compliant"
        },
        "tags": {
            "NameOfKey": "String value"
        },
        "data": {
            "ResourceHomeRegionID": "{data_partition_id}:reference-data--OSDURegion:AWSEastUSA:",
            "ResourceHostRegionIDs": [
                "{data_partition_id}:reference-data--OSDURegion:AWSEastUSA:"
            ],
            "ResourceCurationStatus": "{data_partition_id}:reference-data--ResourceCurationStatus:Created:",
            "ResourceLifecycleStatus": "{data_partition_id}:reference-data--ResourceLifecycleStatus:Loading:",
            "ResourceSecurityClassification": "{data_partition_id}:reference-data--ResourceSecurityClassification:Public:",
            "Source": "Example Data Source",
            "ExistenceKind": "{data_partition_id}:reference-data--ExistenceKind:Prototype:",
            "Datasets": [
                "{data_partition_id}:dataset--AnyDataset:SomeUniqueAnyDatasetID:"
            ],
            "TechnicalAssurances": [
                {
                    "TechnicalAssuranceTypeID": "{data_partition_id}:reference-data--TechnicalAssuranceType:Trusted:",
                    "Reviewers": [
                        {
                            "RoleTypeID": "{data_partition_id}:reference-data--ContactRoleType:AccountOwner:",
                            "DataGovernanceRoleTypeID": "{data_partition_id}:reference-data--DataGovernanceRoleType:SME:",
                            "WorkflowPersonaTypeID": "{data_partition_id}:reference-data--WorkflowPersonaType:SeismicProcessor:",
                            "OrganisationID": "{data_partition_id}:master-data--Organisation:SomeUniqueOrganisationID:",
                            "Name": "John Smith"
                        }
                    ],
                    "AcceptableUsage": [
                        {
                            "WorkflowUsageTypeID": "{data_partition_id}:reference-data--WorkflowUsageType:SeismicProcessing:",
                            "WorkflowPersonaTypeID": "{data_partition_id}:reference-data--WorkflowPersonaType:SeismicProcessor:",
                            "DataQualityRuleSetID": "{data_partition_id}:reference-data--DataQualityRuleSet:SeismicProcessingQCRuleSet:",
                            "DataQualityID": "{data_partition_id}:work-product-component--DataQuality:6a433d16-07c8-4f4d-9ddc-5608e2ec4234:1562066077849221",
                            "ValueChainStatusTypeID": "{data_partition_id}:reference-data--ValueChainStatusType:Exploration:"
                        }
                    ],
                    "UnacceptableUsage": [
                        {
                            "WorkflowUsageTypeID": "{data_partition_id}:reference-data--WorkflowUsageType:SeismicInterpretation:",
                            "WorkflowPersonaTypeID": "{data_partition_id}:reference-data--WorkflowPersonaType:SeismicInterpreter:",
                            "DataQualityRuleSetID": "{data_partition_id}:reference-data--DataQualityRuleSet:SeismicInterpretationQCRuleSet:",
                            "DataQualityID": "{data_partition_id}:work-product-component--DataQuality:d79bf97c-ff7c-4b82-89b5-c88520c15017:1562066009929332",
                            "ValueChainStatusTypeID": "{data_partition_id}:reference-data--ValueChainStatusType:FieldDevelopment:"
                        }
                    ],
                    "EffectiveDate": "2020-02-13",
                    "Comment": "This is free form text from reviewer, e.g. restrictions on use"
                }
            ],
            "NameAliases": [
                {
                    "AliasName": "Example AliasName",
                    "AliasNameTypeID": "{data_partition_id}:reference-data--AliasNameType:RegulatoryIdentifier:",
                    "DefinitionOrganisationID": "{data_partition_id}:master-data--Organisation:SomeUniqueOrganisationID:",
                    "EffectiveDateTime": "2020-02-13T09:13:15.55Z",
                    "TerminationDateTime": "2020-02-13T09:13:15.55Z"
                }
            ],
            "Name": "Example Name",
            "Description": "Example Description",
            "CreationDateTime": "2020-02-13T09:13:15.55Z",
            "Tags": [
                "Example Tags"
            ],
            "SubmitterName": "Example SubmitterName",
            "BusinessActivities": [
                "Example BusinessActivities"
            ],
            "AuthorIDs": [
                "Example AuthorIDs"
            ],
            "LineageAssertions": [
                {
                    "ID": "{data_partition_id}:any-group-type--AnyIndividualType:SomeUniqueAnyIndividualTypeID:",
                    "LineageRelationshipType": "{data_partition_id}:reference-data--LineageRelationshipType:Direct:"
                }
            ],
            "DocumentTypeID": "{data_partition_id}:reference-data--DocumentType:Affidavit:",
            "NumberOfPages": 2,
            "SubTitle": "Example SubTitle",
            "DocumentSubject": "Example DocumentSubject",
            "DatePublished": "2020-02-13T09:13:15.55Z",
            "DateModified": "2020-02-13T09:13:15.55Z",
            "DocumentLanguage": "eng",
            "SampleIDs": [
                "{data_partition_id}:master-data--Sample:Kentish-Knock-South-1_KK-16:",
                "{data_partition_id}:master-data--Sample:Kentish-Knock-South-1_KK-17:",
                "{data_partition_id}:master-data--Sample:Kentish-Knock-South-1_KK-21:"
            ],
            "ReportSampleIdentifiers": [
                "KK-16",
                "KK-17",
                "KK-21"
            ],
            "SampleAnalysisTypeIDs": [
                "{data_partition_id}:reference-data--SampleAnalysisType:NMR:",
                "{data_partition_id}:reference-data--SampleAnalysisType:ElectricalProperties.CoCw:",
                "{data_partition_id}:reference-data--SampleAnalysisType:PVT.MultiStageSeparatorTest:",
                "{data_partition_id}:reference-data--SampleAnalysisType:GasChromatographyMassSpectroscopy.Saturate:"
            ],
            "SamplesAnalysisCategoryTagIDs": [
                "{data_partition_id}:reference-data--SamplesAnalysisCategoryTag:ExxonMobil-SCAL:"
            ],
            "Remarks": [
                {
                    "RemarkSequenceNumber": 1,
                    "Remark": "Example Remark",
                    "RemarkSource": "Example Remark Source",
                    "RemarkDate": "2020-02-13"
                }
            ],
            "LaboratoryIDs": [
                "{data_partition_id}:master-data--Organisation:SomeUniqueOrganisationID:"
            ],
            "LaboratoryNames": [
                "Example LaboratoryNames"
            ],
            "ExtensionProperties": {}
        }
    }
]

=== sharad-adapts/rafs-ddms/tests/integration/data/constant_volume_depletion/cvd.json
{
        "id": "{data_partition_id}:work-product-component--ConstantVolumeDepletionTest:{record_id}",
        "kind": "{custom_schema_authority}:wks:work-product-component--ConstantVolumeDepletionTest:{schema_version}",
        "acl": {
            "owners": ["{acl_viewers}"],
            "viewers": ["{acl_owners}"]
        },
        "legal": {
            "legaltags": ["{legal_tag}"],
            "otherRelevantDataCountries": [
                "US"
            ],
            "status": "compliant"
        },
        "tags": {
            "tag1": "Report for PVT",
            "tag2": "Report for PVT"
        },
        "meta": [],
        "data": {
            "Datasets": [
                "{data_partition_id}:dataset--File.Generic:dataset_test:"
            ],
            "PVTReportID":"{pvt_record_id}:",
            "FluidSampleID": "{data_partition_id}:master-data--FluidSample:fluid_sample_test:",
            "AnalysisDate": "2023-03-23",
            "LabSampleIdentifier": "20207905-20",
            "LaboratoryName": "Lab",
            "Remarks": [
                {
                    "Remark": "Mounted",
                    "RemarkID": "Remark 1",
                    "RemarkSource": "RemarkSource"
                }
            ],
            "DDMSDatasets": []
        }
}

=== sharad-adapts/rafs-ddms/tests/integration/data/v2/sar.json
{
    "id": "{data_partition_id}:work-product-component--SamplesAnalysesReport:{record_id}",
    "kind": "{schema_authority}:wks:work-product-component--SamplesAnalysesReport:{schema_version}",
    "acl": {
        "viewers": ["{acl_viewers}"],
        "owners": ["{acl_owners}"]
    },
    "legal": {
        "legaltags": ["{legal_tag}"],
        "otherRelevantDataCountries": [
            "US"
        ],
        "status": "compliant"
    },
    "tags": {
        "NameOfKey": "String value"
    },
    "meta": [],
    "data": {
        "DocumentTypeID": "{data_partition_id}:reference-data--DocumentType:SampleAnalysisReport:",
        "NumberOfPages": 45,
        "SubTitle": "Advanced Core Analysis Study",
        "DocumentSubject": "SCAL Results Report (Final)",
        "DatePublished": "2020-12-16T11:46:20.163Z",
        "DateModified": "2020-12-16T11:46:20.163Z",
        "DocumentLanguage": "English",
        "SampleIDs": [
            "{data_partition_id}:master-data--Sample:dd76cf6c-226f-5636-ad1b-1ca0f8249cc10:"
        ],
        "ReportSampleIdentifiers": [
            "45H"
        ],
        "SampleAnalysisTypeIDs": [
            "{data_partition_id}:reference-data--SampleAnalysisType:CapillaryPressure.Centrifuge:"
        ],
        "SamplesAnalysisCategoryTagIDs": [
            "{data_partition_id}:reference-data--SamplesAnalysisCategoryTag:GreenCompany.SCAL:"
        ],
        "Remarks": [
            {
                "Remark": "Test was successfully conducted",
                "RemarkSequenceNumber": 1,
                "RemarkSource": "Lab"
            }
        ],
        "LaboratoryIDs": [
            "{data_partition_id}:master-data--Organisation:OrganisationName:"
        ],
        "LaboratoryNames": [
            "Lab1"
        ]
    }
}

=== sharad-adapts/rafs-ddms/tests/integration/data/v2/osdu_generic_record.json
{
    "id": "",
    "kind": "",
    "acl": {
        "viewers": ["{acl_viewers}"],
        "owners": ["{acl_owners}"]
    },
    "legal": {
        "legaltags": ["{legal_tag}"],
        "otherRelevantDataCountries": [
            "US"
        ],
        "status": "compliant"
    },
    "tags": {
        "NameOfKey": "String value"
    },
    "meta": [],
    "data": {
        "dummy": "data"
    }
}
