=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/gas_composition_data_schema.json
{
  "x-osdu-review-status": "Pending",
  "$id": "https://schema.osdu.opengroup.org/json/content/GasCompositionDataSchema.1.0.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GasCompositionDataSchema",
  "description": "GasCompositionDataSchema",
  "type": "object",
  "properties": {
    "SamplesAnalysisID": {
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "EntityType": "SamplesAnalysis",
          "GroupType": "work-product-component"
        }
      ]
    },
    "SampleID": {
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "EntityType": "Sample",
          "GroupType": "master-data"
        }
      ]
    },
    "Method": {
      "type": "string",
      "description": "The sample analysis method used for this analysis",
      "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-BulkPyrolysisMethod:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "EntityType": "BulkPyrolysisMethod",
          "GroupType": "reference-data"
        }
      ]
    },
    "GasComposition": {
      "title": "Gas Composition",
      "description": "The relative abundance of hydrocarbon gases measured using gas chromatography",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Component": {
            "type": "string",
            "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-GasCompositionComponents:[\\w\\-\\.\\:\\%]+:[0-9]*$",
            "x-osdu-relationship": [
              {
                "EntityType": "GasCompositionComponents",
                "GroupType": "reference-data"
              }
            ]
          },
          "Concentration": {
            "type": "object",
            "description": "the concentration of the gas component in the overall hydrocarbon gas composition",
            "properties": {
              "Value": {
                "type": "number"
              },
              "UnitOfMeasure": {
                "type": "string",
                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                "x-osdu-relationship": [
                  {
                    "EntityType": "UnitOfMeasure",
                    "GroupType": "reference-data"
                  }
                ]
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    },
    "Ratios": {
      "type": "object",
      "properties": {
        "WetnessC5": {
          "type": "object",
          "description": "Gas Wetness (C2-C5) / (C1-C5)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "WetnessC4": {
          "type": "object",
          "description": "Gas Wetness (C2-C4) / (C1-C4)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "DrynessC5": {
          "type": "object",
          "description": "Gas Dryness ratio (C1) / (C1-C5)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "DrynessC4": {
          "type": "object",
          "description": "Gas Dryness ratio (C1) / (C1-C4)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "Maturity": {
          "type": "object",
          "description": "Gas Maturity ratio iso-butane / normal-pentane",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "Balance": {
          "type": "object",
          "description": "Balance ratio C1+C2/C3+C4+C5",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "Character": {
          "type": "object",
          "description": "Character ratio C4+C5/C3",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "GasIndicator": {
          "type": "object",
          "description": "Gas Indicator ratio ((C3+C4+C5) * Total Gas) / (C1+C2+C3+C4+C5)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "OilIndicator": {
          "type": "object",
          "description": "Oil Indicator ratio ((C3+C4)/C1)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "Bernard": {
          "type": "object",
          "description": "Bernard ratio - Methane / Ethane + Propane (%)",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "SamplesAnalysisID",
    "SampleID"
  ],
  "additionalProperties": false
}

=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/gas_composition_data_example.json
{
    "SamplesAnalysisID": "opendes:work-product-component--SamplesAnalysis:GasComposition_WPC:",
    "SampleID": "opendes:master-data--Sample:GasCompositionSample:",
    "Method": "SampleMethod",
    "GasComposition": [
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      },
      {
        "Component": "opendes:reference-data--GasChromatographyGasCompositionComponents:acetylene:",
        "Concentration": {
          "Value": 0.0,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
        }
      }
    ],
    "Ratios": {
      "WetnessC5": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "WetnessC4": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "DrynessC5": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "DrynessC4": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "Maturity": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "Balance": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "Character": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "GasIndicator": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "OilIndicator": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      },
      "Bernard": {
        "Value": 0.0,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
      }
    }
  }
