=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/gcmsms_data_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "SamplesAnalysisID": {
            "type": "string",
            "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$"
        },
        "SampleID": {
            "type": "string",
            "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$"
        },
        "GasChromatographyTandemMassSpectrometryAnalysis": {
            "title": "Gas Chromatography Tandem Mass Spectrometry Analysis",
            "description": "Gas Chromatography-Tandem Mass spectrometry (GC-MS-MS) couples a Gas Chromatograph (GC) with two Mass Spectrometers which increases detail in molecular structure analysis.  This analysis includes QQQ (Triple Quadrupole) and MRM (Multiple Reaction Monitoring)",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "CompoundCode": {
                        "type": "string",
                        "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-GasChromatographyTandemMassSpectrometrySaturateCompounds:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                    },
                    "RetentionTime": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    },
                    "Ions": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "Peak": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "Value": {
                                    "type": "number"
                                },
                                "UnitOfMeasure": {
                                    "type": "string",
                                    "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                                },
                                "AreaHeightQualifier": {
                                    "type": "string",
                                    "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-CompoundsAreaHeight:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                                }
                            },
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false
            }
        },
        "StdCompound": {
            "description": "Compound added as internal standard",
            "type": "object",
            "properties": {
                "CompoundCode": {
                    "type": "string",
                    "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-GasChromatographyTandemMassSpectrometrySaturateCompounds:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                },
                "RetentionTime": {
                    "type": "object",
                    "properties": {
                        "Value": {
                            "type": "number"
                        },
                        "UnitOfMeasure": {
                            "type": "string",
                            "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                        }
                    },
                    "additionalProperties": false
                },
                "Ions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Peak": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            },
                            "AreaHeightQualifier": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-CompoundsAreaHeight:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "SamplesAnalysisID",
        "SampleID"
    ],
    "additionalProperties": false
}

=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/gcmsms_data_example.json
{
    "SamplesAnalysisID": "opendes:work-product-component--SamplesAnalysis:GCMSMS_SamplesAnalysis:",
    "SampleID": "opendes:master-data--Sample:GCMSMS_Sample:",
    "GasChromatographyTandemMassSpectrometryAnalysis": [
        {
            "CompoundCode": "opendes:reference-data--GCMSMSCompounds:Abietane:",
            "RetentionTime": {
                "Value": 1.0,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
            },
            "Ions": [
                "ABCDEFGHIJKL"
            ],
            "Peak": [
                {
                    "Value": 1.0,
                    "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
                    "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:Height:"
                }
            ]
        }
    ],
    "StdCompound": {
        "CompoundCode": "opendes:reference-data--GCMSMSCompounds:Beyerane:",
        "RetentionTime": {
            "Value": 1.0,
            "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
        },
        "Ions": [
            "ABCD",
            "ABCDEFGHIJKLMN"
        ],
        "Peak": [
            {
                "Value": 1.0,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
                "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:Height:"
            },
            {
                "Value": 1.0,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
                "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:Height:"
            }
        ]
    }
}
