=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/gcms_alkanes_data_schema.json
{
  "x-osdu-review-status": "Pending",
  "$id": "https://schema.osdu.opengroup.org/json/content/GcmsAlkanesDataSchema.1.0.0.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GcmsAlkanesDataSchema",
  "description": "GcmsAlkanesDataSchema",
  "type": "object",
  "properties": {
    "SamplesAnalysisID": {
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "EntityType": "SamplesAnalysis",
          "GroupType": "work-product-component"
        }
      ]
    },
    "SampleID": {
      "type": "string",
      "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "EntityType": "Sample",
          "GroupType": "master-data"
        }
      ]
    },
    "Method": {
      "type": "string",
      "description": "The sample analysis method used for this analysis",
      "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-BulkPyrolysisMethod:[\\w\\-\\.\\:\\%]+:[0-9]*$",
      "x-osdu-relationship": [
        {
          "EntityType": "BulkPyrolysisMethod",
          "GroupType": "reference-data"
        }
      ]
    },
    "SaturateGCMSCompounds": {
      "title": "Saturate Compounds",
      "description": "The list of compounds in Saturate Gas Chromatography Mass Spectrometry (GCMS) analysis",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "CompoundCode": {
            "type": "string",
            "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-SaturateGCMSCompounds:[\\w\\-\\.\\:\\%]+:[0-9]*$",
            "x-osdu-relationship": [
              {
                "EntityType": "SaturateGCMSCompounds",
                "GroupType": "reference-data"
              }
            ]
          },
          "RetentionTime": {
            "type": "object",
            "properties": {
              "Value": {
                "type": "number"
              },
              "UnitOfMeasure": {
                "type": "string",
                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                "x-osdu-relationship": [
                  {
                    "EntityType": "UnitOfMeasure",
                    "GroupType": "reference-data"
                  }
                ]
              }
            },
            "additionalProperties": false
          },
          "Ion": {
            "type": "string"
          },
          "Peak": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Value": {
                  "type": "number"
                },
                "UnitOfMeasure": {
                  "type": "string",
                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                  "x-osdu-relationship": [
                    {
                      "EntityType": "UnitOfMeasure",
                      "GroupType": "reference-data"
                    }
                  ]
                },
                "AreaHeightQualifier": {
                  "type": "string",
                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-CompoundsAreaHeight:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                  "x-osdu-relationship": [
                    {
                      "EntityType": "CompoundsAreaHeight",
                      "GroupType": "reference-data"
                    }
                  ]
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false
      }
    },
    "StdCompound": {
      "description": "Compound added as internal standard",
      "type": "object",
      "properties": {
        "CompoundCode": {
          "type": "string",
          "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-SaturateGCMSCompounds:[\\w\\-\\.\\:\\%]+:[0-9]*$",
          "x-osdu-relationship": [
            {
              "EntityType": "SaturateGCMSCompounds",
              "GroupType": "reference-data"
            }
          ]
        },
        "RetentionTime": {
          "type": "object",
          "properties": {
            "Value": {
              "type": "number"
            },
            "UnitOfMeasure": {
              "type": "string",
              "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
              "x-osdu-relationship": [
                {
                  "EntityType": "UnitOfMeasure",
                  "GroupType": "reference-data"
                }
              ]
            }
          },
          "additionalProperties": false
        },
        "Ion": {
          "type": "string"
        },
        "Peak": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Value": {
                "type": "number"
              },
              "UnitOfMeasure": {
                "type": "string",
                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                "x-osdu-relationship": [
                  {
                    "EntityType": "UnitOfMeasure",
                    "GroupType": "reference-data"
                  }
                ]
              },
              "AreaHeightQualifier": {
                "type": "string",
                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-CompoundsAreaHeight:[\\w\\-\\.\\:\\%]+:[0-9]*$",
                "x-osdu-relationship": [
                  {
                    "EntityType": "CompoundsAreaHeight",
                    "GroupType": "reference-data"
                  }
                ]
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "SamplesAnalysisID",
    "SampleID"
  ],
  "additionalProperties": false
}

=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/gcms_alkanes_data_example.json
{
  "SamplesAnalysisID": "opendes:work-product-component--SamplesAnalysis:GCMS_Alkanes_Example:",
  "SampleID": "opendes:master-data--Sample:TestSample:",
  "Method": "opendes:reference-data--BulkPyrolysisMethod:HAWK:",
  "SaturateGCMSCompounds": [
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:chol5b:",
      "RetentionTime": {
        "Value": 1.1,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHI",
      "Peak": [
        {
          "Value": 2.2,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:HEIGHT:"
        }
      ]
    },
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:gcar:",
      "RetentionTime": {
        "Value": 3.3,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      "Peak": [
        {
          "Value": 4.4,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:HEIGHT:"
        }
      ]
    },
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:t22:",
      "RetentionTime": {
        "Value": 9.9,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHIJKLMNOPQR",
      "Peak": [
        {
          "Value": 1.1,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:AREA:"
        },
        {
          "Value": 2.2,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:AREA:"
        }
      ]
    },
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:t24:",
      "RetentionTime": {
        "Value": 5.5,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHIJ",
      "Peak": [
        {
          "Value": 6.6,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:HEIGHT:"
        }
      ]
    },
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:t24o:",
      "RetentionTime": {
        "Value": 9.9,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHIJKL",
      "Peak": [
        {
          "Value": 1.1,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:AREA:"
        },
        {
          "Value": 2.2,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:AREA:"
        }
      ]
    },
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:c24delup:",
      "RetentionTime": {
        "Value": 4.4,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHIJKL",
      "Peak": []
    },
    {
      "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:t25:",
      "RetentionTime": {
        "Value": 5.5,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
      },
      "Ion": "ABCDEFGHIJKL",
      "Peak": [
        {
          "Value": 6.6,
          "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
          "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:HEIGHT:"
        }
      ]
    }
  ],
  "StdCompound": {
    "CompoundCode": "opendes:reference-data--SaturateGCMSCompounds:c24deurs:",
    "RetentionTime": {
      "Value": 8.8,
      "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:"
    },
    "Ion": "ABCDEFGHI",
    "Peak": [
      {
        "Value": 1.1,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:s:",
        "AreaHeightQualifier": "opendes:reference-data--CompoundsAreaHeight:HEIGHT:"
      }
    ]
  }
}
