=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/multiple_salinity_data_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "SamplesAnalysisID": {
            "type": "string",
            "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$"
        },
        "TestMethod": {
            "type": "string"
        },
        "SalinityTestResults": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "SampleID": {
                        "type": "string",
                        "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                    },
                    "BQv": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    },
                    "Qv": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    },
                    "BrineResistivity": {
                        "type": "object",
                        "properties": {
                            "Value": {
                    
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    },
                    "AdjustedFormationResistivityFactor": {
                        "type": "number"
                    },
                    "AdjustedSaturationExponent": {
                        "type": "number"
                    },
                    "WaterSaturationOverResistivity": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "ResistivityIndex": {
                                    "type": "number"
                                },
                                "WaterSaturation": {
                                    "type": "object",
                                    "properties": {
                                        "Value": {
                                            "type": "number"
                                        },
                                        "UnitOfMeasure": {
                                            "type": "string",
                                            "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                                        }
                                    },
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false
            }
        },
        "SalinityTestSteps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "BrineSalinity": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    },
                    "BrineConductivity": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    },
                    "CoreConductivity": {
                        "type": "object",
                        "properties": {
                            "Value": {
                                "type": "number"
                            },
                            "UnitOfMeasure": {
                                "type": "string",
                                "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "SamplesAnalysisID"
    ]
}

=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/multiple_salinity_data_example.json
{
    "SamplesAnalysisID": "osdu:work-product-component--SamplesAnalysis:Multiple_Salinity_Example:",
    "TestMethod": "TestMethod",
    "SalinityTestResults": [
        {
            "SampleID": "osdu:master-data--Sample:88Y:",
            "BQv": {
                "Value": 3.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            },
            "Qv": {
                "Value": 3.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            }
        },
        {
            "SampleID": "osdu:master-data--Sample:88Y:",
            "BQv": {
                "Value": 4.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            },
            "Qv": {
                "Value": 4.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            }
        }
    ],
    "SalinityTestSteps": [
        {
            "BrineSalinity": {
                "Value": 3.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            },
            "BrineConductivity": {
                "Value": 3.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            },
            "CoreConductivity": {
                "Value": 3.5,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:%25:"
            }
        }
    ]
}
