=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/transport_test_data_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
      "SamplesAnalysisID": {
          "type": "string",
          "pattern": "^[\\w\\-\\.]+:work-product-component\\-\\-SamplesAnalysis:[\\w\\-\\.\\:\\%]+:[0-9]*$"
      },
      "SampleID": {
          "type": "string",
          "pattern": "^[\\w\\-\\.]+:master-data\\-\\-Sample:[\\w\\-\\.\\:\\%]+:[0-9]*$"
      },
      "TestNumber": {
          "title": "Test Number",
          "type": "string",
          "description": "A number for this test for purposes of e.g., tracking lab sequence."
      },
      "TestTemperature": {
          "type": "object",
          "properties": {
              "Value": {
                  "type": "number"
              },
              "UnitOfMeasure": {
                  "type": "string",
                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
              }
          },
          "additionalProperties": false
      },
      "SaturationPressure": {
          "type": "object",
          "properties": {
              "Value": {
                  "type": "number"
              },
              "UnitOfMeasure": {
                  "type": "string",
                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
              }
          },
          "additionalProperties": false
      },
      "TransportTestSteps": {
          "type": "array",
          "items": [
              {
                  "type": "object",
                  "properties": {
                      "StepNumber": {
                          "type": "string",
                          "title": "Step Number",
                          "description": "Internal step number which identifies the sequence of step in transport test measurements"
                      },
                      "StepPressure": {
                          "type": "object",
                          "properties": {
                              "Value": {
                                  "type": "number"
                              },
                              "UnitOfMeasure": {
                                  "type": "string",
                                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                              }
                          },
                          "additionalProperties": false
                      },
                      "OilViscosity": {
                          "type": "object",
                          "properties": {
                              "Value": {
                                  "type": "number"
                              },
                              "UnitOfMeasure": {
                                  "type": "string",
                                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                              }
                          },
                          "additionalProperties": false
                      },
                      "GasViscosity": {
                          "type": "object",
                          "properties": {
                              "Value": {
                                  "type": "number"
                              },
                              "UnitOfMeasure": {
                                  "type": "string",
                                  "pattern": "^[\\w\\-\\.]+:reference-data\\-\\-UnitOfMeasure:[\\w\\-\\.\\:\\%]+:[0-9]*$"
                              }
                          },
                          "additionalProperties": false
                      }
                  },
                  "additionalProperties": false
              }
          ]
      }
  },
  "additionalProperties": false,
  "required": [
      "SamplesAnalysisID",
      "SampleID"
  ]
}

=== sharad-adapts/rafs-ddms/app/models/data_schemas/jsonschema/api_v2/transport_test_data_example.json
{
    "SamplesAnalysisID": "opendes:work-product-component--SamplesAnalysis:samplesanalysis_test:",
    "SampleID": "opendes:master-data--Sample:fluid_sample_test:",
    "TestNumber": "test_number",
    "TestTemperature": {
        "Value": 273,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:degF:"
    },
    "SaturationPressure": {
        "Value": 4634,
        "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:psia:"
    },
    "TransportTestSteps": [
        {
            "StepNumber": "1",
            "StepPressure": {
                "Value": 4634,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:psia:"
            },
            "OilViscosity": {
                "Value": 15,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:cP:"
            },
            "GasViscosity": {
                "Value": 20,
                "UnitOfMeasure": "opendes:reference-data--UnitOfMeasure:cP:"
            }
        }
    ]
}
